module []

import Dotenv

# Generated by scripts/generate_roc_tests.py from test/cases/*.json.
# Edit the JSON contract cases, then regenerate this file.

# parses unquoted assignment
expect
    Dotenv.parseString("FOO=bar", []) == Ok([{ key: "FOO", value: "bar" }])

# trims whitespace around equals
expect
    Dotenv.parseString("FOO =bar", []) == Ok([{ key: "FOO", value: "bar" }])

# trims whitespace before value
expect
    Dotenv.parseString("FOO= bar", []) == Ok([{ key: "FOO", value: "bar" }])

# parses yaml-style assignment
expect
    Dotenv.parseString("OPTION_A: 1", []) == Ok([{ key: "OPTION_A", value: "1" }])

# keeps equals signs inside yaml-style values
expect
    Dotenv.parseString("OPTION_A: Foo=bar", []) == Ok([{ key: "OPTION_A", value: "Foo=bar" }])

# keeps colons inside equals-style values
expect
    Dotenv.parseString("OPTION_A=1:B", []) == Ok([{ key: "OPTION_A", value: "1:B" }])

# parses export keyword
expect
    Dotenv.parseString("export OPTION_A=2", []) == Ok([{ key: "OPTION_A", value: "2" }])

# parses tab after export keyword
expect
    Dotenv.parseString("export\tOPTION_A=2", []) == Ok([{ key: "OPTION_A", value: "2" }])

# allows dots in key names
expect
    Dotenv.parseString("FOO.BAR=foobar", []) == Ok([{ key: "FOO.BAR", value: "foobar" }])

# allows hyphens in key names
expect
    Dotenv.parseString("OPTION-B=def", []) == Ok([{ key: "OPTION-B", value: "def" }])

# keeps trailing equals signs in values
expect
    Dotenv.parseString("FOO=foobar=", []) == Ok([{ key: "FOO", value: "foobar=" }])

# ignores inline comments after whitespace
expect
    Dotenv.parseString("FOO=bar # this is foo", []) == Ok([{ key: "FOO", value: "bar" }])

# keeps hash characters in double quoted values
expect
    Dotenv.parseString("FOO=\"bar#baz\" # comment", []) == Ok([{ key: "FOO", value: "bar#baz" }])

# keeps hash characters in single quoted values
expect
    Dotenv.parseString("FOO='bar#baz' # comment", []) == Ok([{ key: "FOO", value: "bar#baz" }])

# expands escaped newline in double quoted values
expect
    Dotenv.parseString("FOO=\"bar\\nbaz\"", []) == Ok([{ key: "FOO", value: "bar\nbaz" }])

# unescapes escaped double quotes
expect
    Dotenv.parseString("FOO=\"escaped\\\"bar\"", []) == Ok([{ key: "FOO", value: "escaped\"bar" }])

# does not let trailing escaped backslash escape closing quote
expect
    Dotenv.parseString("FOO=\"bar\\\\\"", []) == Ok([{ key: "FOO", value: "bar\\" }])

# trims leading whitespace before key
expect
    Dotenv.parseString(" KEY =value", []) == Ok([{ key: "KEY", value: "value" }])

# trims leading tab before key
expect
    Dotenv.parseString("\tKEY=value", []) == Ok([{ key: "KEY", value: "value" }])

# preserves internal whitespace with trailing newline
expect
    Dotenv.parseString("KEY=value value\n", []) == Ok([{ key: "KEY", value: "value value" }])

# rejects plus signs in key names
expect
    Dotenv.parseString("FOO+BAR=baz", []) == Err(UnexpectedChar)

# rejects unterminated quoted values
expect
    Dotenv.parseString("foo=\"bar", []) == Err(UnterminatedQuote)

# parses plain fixture
expect
    Dotenv.parseString("OPTION_A=1\nOPTION_B=2\nOPTION_C= 3\nOPTION_D =4\nOPTION_E = 5\nOPTION_F = \nOPTION_G=\nOPTION_H=1 2", []) == Ok([{ key: "OPTION_A", value: "1" }, { key: "OPTION_B", value: "2" }, { key: "OPTION_C", value: "3" }, { key: "OPTION_D", value: "4" }, { key: "OPTION_E", value: "5" }, { key: "OPTION_F", value: "" }, { key: "OPTION_G", value: "" }, { key: "OPTION_H", value: "1 2" }])

# parses exported fixture
expect
    Dotenv.parseString("export OPTION_A=2\nexport OPTION_B='\\n'\n", []) == Ok([{ key: "OPTION_A", value: "2" }, { key: "OPTION_B", value: "\\n" }])

# parses equals fixture
expect
    Dotenv.parseString("export OPTION_A='postgres://localhost:5432/database?sslmode=disable'", []) == Ok([{ key: "OPTION_A", value: "postgres://localhost:5432/database?sslmode=disable" }])

# parses hyphen fixture
expect
    Dotenv.parseString("OPTION_A=abc\nOPTION-B=def\n", []) == Ok([{ key: "OPTION_A", value: "abc" }, { key: "OPTION-B", value: "def" }])

# parses comments fixture
expect
    Dotenv.parseString("# Full line comment\nqux=thud # fred # other\nthud=fred#qux # other\nfred=qux#baz # other # more\nfoo=bar # baz\nbar=foo#baz\nbaz=\"foo\"#bar\n", []) == Ok([{ key: "qux", value: "thud" }, { key: "thud", value: "fred#qux" }, { key: "fred", value: "qux#baz" }, { key: "foo", value: "bar" }, { key: "bar", value: "foo#baz" }, { key: "baz", value: "foo" }])

# expands substitutions fixture using explicit existing env
expect
    Dotenv.parseString("OPTION_A=1\nOPTION_B=\${OPTION_A}\nOPTION_C=$OPTION_B\nOPTION_D=\${OPTION_A}\${OPTION_B}\nOPTION_E=\${OPTION_NOT_DEFINED}\nOPTION_F=\${GLOBAL_OPTION}\n", [{ key: "GLOBAL_OPTION", value: "global" }]) == Ok([{ key: "OPTION_A", value: "1" }, { key: "OPTION_B", value: "1" }, { key: "OPTION_C", value: "1" }, { key: "OPTION_D", value: "11" }, { key: "OPTION_E", value: "" }, { key: "OPTION_F", value: "global" }])

# parses quoted fixture
expect
    Dotenv.parseString("OPTION_A='1'\nOPTION_B='2'\nOPTION_C=''\nOPTION_D='\\n'\nOPTION_E=\"1\"\nOPTION_F=\"2\"\nOPTION_G=\"\"\nOPTION_H=\"\\n\"\nOPTION_I = \"echo 'asd'\"\nOPTION_J='line 1\nline 2'\nOPTION_K='line one\nthis is \\'quoted\\'\none more line'\nOPTION_L=\"line 1\nline 2\"\nOPTION_M=\"line one\nthis is \\\"quoted\\\"\none more line\"", []) == Ok([{ key: "OPTION_A", value: "1" }, { key: "OPTION_B", value: "2" }, { key: "OPTION_C", value: "" }, { key: "OPTION_D", value: "\\n" }, { key: "OPTION_E", value: "1" }, { key: "OPTION_F", value: "2" }, { key: "OPTION_G", value: "" }, { key: "OPTION_H", value: "\n" }, { key: "OPTION_I", value: "echo 'asd'" }, { key: "OPTION_J", value: "line 1\nline 2" }, { key: "OPTION_K", value: "line one\nthis is \\'quoted\\'\none more line" }, { key: "OPTION_L", value: "line 1\nline 2" }, { key: "OPTION_M", value: "line one\nthis is \"quoted\"\none more line" }])

# parses multiple assignments from string input
expect
    Dotenv.parseString("ONE=1\nTWO='2'\nTHREE = \"3\"", []) == Ok([{ key: "ONE", value: "1" }, { key: "TWO", value: "2" }, { key: "THREE", value: "3" }])

# parses double quoted values
expect
    Dotenv.parseString("FOO=\"bar\"", []) == Ok([{ key: "FOO", value: "bar" }])

# parses single quoted values
expect
    Dotenv.parseString("FOO='bar'", []) == Ok([{ key: "FOO", value: "bar" }])

# parses single quotes inside double quotes
expect
    Dotenv.parseString("FOO=\"'d'\"", []) == Ok([{ key: "FOO", value: "'d'" }])

# parses export-looking keys without trimming export
expect
    Dotenv.parseString("exportFoo=2", []) == Ok([{ key: "exportFoo", value: "2" }])

# parses keys prefixed with export without whitespace
expect
    Dotenv.parseString("exportFOO=2", []) == Ok([{ key: "exportFOO", value: "2" }])

# parses underscored export key
expect
    Dotenv.parseString("export_FOO =2", []) == Ok([{ key: "export_FOO", value: "2" }])

# parses dotted export key
expect
    Dotenv.parseString("export.FOO= 2", []) == Ok([{ key: "export.FOO", value: "2" }])

# parses export after leading space
expect
    Dotenv.parseString(" export OPTION_A=2", []) == Ok([{ key: "OPTION_A", value: "2" }])

# parses export after leading tab
expect
    Dotenv.parseString("\texport OPTION_A=2", []) == Ok([{ key: "OPTION_A", value: "2" }])

# allows an empty key name
expect
    Dotenv.parseString("=\"value\"", []) == Ok([{ key: "", value: "value" }])

# ignores blank input
expect
    Dotenv.parseString("\n", []) == Ok([])

# ignores windows-style blank input
expect
    Dotenv.parseString("\r\n", []) == Ok([])

# ignores whitespace-only input
expect
    Dotenv.parseString("\t\t ", []) == Ok([])

# ignores full-line comments
expect
    Dotenv.parseString("# Comment", []) == Ok([])

# ignores indented comments
expect
    Dotenv.parseString("\t # comment", []) == Ok([])

# skips multiple consecutive comments before value
expect
    Dotenv.parseString("# one\n# two\n# three\nFOO=bar", []) == Ok([{ key: "FOO", value: "bar" }])

# rejects at signs in key names
expect
    Dotenv.parseString("FOO@BAR=baz", []) == Err(UnexpectedChar)

# rejects slashes in key names
expect
    Dotenv.parseString("FOO/BAR=baz", []) == Err(UnexpectedChar)

# rejects invalid fixture
expect
    Dotenv.parseString("INVALID LINE\nfoo=bar\n", []) == Err(UnexpectedChar)

# rejects badly formatted line without separator
expect
    Dotenv.parseString("lol$wut", []) == Err(UnexpectedChar)

# expands variables found in values
expect
    Dotenv.parseString("FOO=test\nBAR=$FOO", []) == Ok([{ key: "FOO", value: "test" }, { key: "BAR", value: "test" }])

# expands variables wrapped in braces
expect
    Dotenv.parseString("FOO=test\nBAR=\${FOO}bar", []) == Ok([{ key: "FOO", value: "test" }, { key: "BAR", value: "testbar" }])

# expands undefined variables to empty string
expect
    Dotenv.parseString("BAR=$FOO", []) == Ok([{ key: "BAR", value: "" }])

# expands variables in double quoted strings
expect
    Dotenv.parseString("FOO=test\nBAR=\"quote $FOO\"", []) == Ok([{ key: "FOO", value: "test" }, { key: "BAR", value: "quote test" }])

# does not expand variables in single quoted strings
expect
    Dotenv.parseString("BAR='quote $FOO'", []) == Ok([{ key: "BAR", value: "quote $FOO" }])

# does not expand escaped dollar variables
expect
    Dotenv.parseString("FOO=\"foo\\$BAR\"", []) == Ok([{ key: "FOO", value: "foo$BAR" }])

# does not expand escaped braced variables
expect
    Dotenv.parseString("FOO=\"foo\\\${BAR}\"", []) == Ok([{ key: "FOO", value: "foo\${BAR}" }])

# expands unescaped braced variables after escaped braced variables
expect
    Dotenv.parseString("FOO=test\nBAR=\"foo\\\${FOO} \${FOO}\"", []) == Ok([{ key: "FOO", value: "test" }, { key: "BAR", value: "foo\${FOO} test" }])

# parses multiline quoted values containing separators
expect
    Dotenv.parseString("TEST_URLS=\"stratum+tcp://stratum.antpool.com:3333\nstratum+tcp://stratum.antpool.com:443\"", []) == Ok([{ key: "TEST_URLS", value: "stratum+tcp://stratum.antpool.com:3333\nstratum+tcp://stratum.antpool.com:443" }])

# parses simple value without trailing newline
expect
    Dotenv.parseString("KEY=value", []) == Ok([{ key: "KEY", value: "value" }])

# parses yaml-style value with internal whitespace without trailing newline
expect
    Dotenv.parseString("KEY: value value", []) == Ok([{ key: "KEY", value: "value value" }])

# parses yaml-style value with internal whitespace with trailing newline
expect
    Dotenv.parseString("KEY: value value\n", []) == Ok([{ key: "KEY", value: "value value" }])

# trims leading mixed whitespace before assignment
expect
    Dotenv.parseString(" \t \t\n\t \t A=a\n", []) == Ok([{ key: "A", value: "a" }])

# trims leading whitespace before export
expect
    Dotenv.parseString(" \t\t export A=a\n", []) == Ok([{ key: "A", value: "a" }])

# trims trailing whitespace
expect
    Dotenv.parseString("A=a \t \t\n", []) == Ok([{ key: "A", value: "a" }])

# trims trailing whitespace with export
expect
    Dotenv.parseString("export A=a\t \t \n", []) == Ok([{ key: "A", value: "a" }])

# trims trailing whitespace with no newline
expect
    Dotenv.parseString("A=a ", []) == Ok([{ key: "A", value: "a" }])

# quotes string values
expect
    Dotenv.marshalEnv([{ key: "key", value: "value" }]) == Ok("key=\"value\"")

# escapes double quotes
expect
    Dotenv.marshalEnv([{ key: "key", value: "va\"lu\"e" }]) == Ok("key=\"va\\\"lu\\\"e\"")

# leaves single quotes alone
expect
    Dotenv.marshalEnv([{ key: "key", value: "va'lu'e" }]) == Ok("key=\"va'lu'e\"")

# escapes newlines carriage returns backslashes and bang
expect
    Dotenv.marshalEnv([{ key: "foo", value: "\n\r\\r!" }]) == Ok("foo=\"\\n\\r\\\\r\\!\"")

# sorts output lines by key
expect
    Dotenv.marshalEnv([{ key: "foo", value: "bar" }, { key: "baz", value: "buzz" }]) == Ok("baz=\"buzz\"\nfoo=\"bar\"")

# does not quote integers
expect
    Dotenv.marshalEnv([{ key: "key", value: "10" }]) == Ok("key=10")

# quotes leading plus values
expect
    Dotenv.marshalEnv([{ key: "key", value: "+123" }]) == Ok("key=\"+123\"")

# preserves leading zero integers
expect
    Dotenv.marshalEnv([{ key: "key", value: "007" }]) == Ok("key=007")

# quotes empty values
expect
    Dotenv.marshalEnv([{ key: "key", value: "" }]) == Ok("key=\"\"")

# quotes alphanumeric values
expect
    Dotenv.marshalEnv([{ key: "key", value: "12a3" }]) == Ok("key=\"12a3\"")

# quotes alphabetic values
expect
    Dotenv.marshalEnv([{ key: "key", value: "abc" }]) == Ok("key=\"abc\"")

# quotes values with internal spaces
expect
    Dotenv.marshalEnv([{ key: "key", value: "12 3" }]) == Ok("key=\"12 3\"")

# quotes lone minus values
expect
    Dotenv.marshalEnv([{ key: "key", value: "-" }]) == Ok("key=\"-\"")

# quotes whitespace-only values
expect
    Dotenv.marshalEnv([{ key: "key", value: " " }]) == Ok("key=\" \"")

# does not quote negative integers
expect
    Dotenv.marshalEnv([{ key: "key", value: "-123" }]) == Ok("key=-123")

# does not quote large negative integers
expect
    Dotenv.marshalEnv([{ key: "key", value: "-922337203685477580868712" }]) == Ok("key=-922337203685477580868712")

# does not quote large positive integers
expect
    Dotenv.marshalEnv([{ key: "key", value: "922337203685477580837281" }]) == Ok("key=922337203685477580837281")

# merges parsed files in order
expect
    Dotenv.mergeParsedFiles([[{ key: "OPTION_A", value: "1" }], [{ key: "OPTION_B", value: "2" }]]) == [{ key: "OPTION_A", value: "1" }, { key: "OPTION_B", value: "2" }]

# preserves existing env without override
expect
    Dotenv.applyParsedEnv([{ key: "OPTION_A", value: "1" }, { key: "OPTION_B", value: "2" }], [{ key: "OPTION_A", value: "do_not_override" }], PreserveExisting) == [{ key: "OPTION_A", value: "do_not_override" }, { key: "OPTION_B", value: "2" }]

# overrides existing env with override policy
expect
    Dotenv.applyParsedEnv([{ key: "OPTION_A", value: "1" }], [{ key: "OPTION_A", value: "do_not_override" }, { key: "OPTION_B", value: "keep" }], OverrideExisting) == [{ key: "OPTION_B", value: "keep" }, { key: "OPTION_A", value: "1" }]

# roundtrips equals fixture
expect
    when Dotenv.parseString("export OPTION_A='postgres://localhost:5432/database?sslmode=disable'", []) is
        Ok(env) ->
            when Dotenv.marshalEnv(env) is
                Ok(serialized) ->
                    Dotenv.parseString(serialized, []) == Ok(env)

                Err(_) ->
                    Bool.false

        Err(_) ->
            Bool.false

# roundtrips exported fixture
expect
    when Dotenv.parseString("export OPTION_A=2\nexport OPTION_B='\\n'\n", []) is
        Ok(env) ->
            when Dotenv.marshalEnv(env) is
                Ok(serialized) ->
                    Dotenv.parseString(serialized, []) == Ok(env)

                Err(_) ->
                    Bool.false

        Err(_) ->
            Bool.false

# roundtrips plain fixture
expect
    when Dotenv.parseString("OPTION_A=1\nOPTION_B=2\nOPTION_C= 3\nOPTION_D =4\nOPTION_E = 5\nOPTION_F = \nOPTION_G=\nOPTION_H=1 2", []) is
        Ok(env) ->
            when Dotenv.marshalEnv(env) is
                Ok(serialized) ->
                    Dotenv.parseString(serialized, []) == Ok(env)

                Err(_) ->
                    Bool.false

        Err(_) ->
            Bool.false

# roundtrips quoted fixture
expect
    when Dotenv.parseString("OPTION_A='1'\nOPTION_B='2'\nOPTION_C=''\nOPTION_D='\\n'\nOPTION_E=\"1\"\nOPTION_F=\"2\"\nOPTION_G=\"\"\nOPTION_H=\"\\n\"\nOPTION_I = \"echo 'asd'\"\nOPTION_J='line 1\nline 2'\nOPTION_K='line one\nthis is \\'quoted\\'\none more line'\nOPTION_L=\"line 1\nline 2\"\nOPTION_M=\"line one\nthis is \\\"quoted\\\"\none more line\"", []) is
        Ok(env) ->
            when Dotenv.marshalEnv(env) is
                Ok(serialized) ->
                    Dotenv.parseString(serialized, []) == Ok(env)

                Err(_) ->
                    Bool.false

        Err(_) ->
            Bool.false
